# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/DCE/Nexys4DDR_Master.xdc

# IP: ip/c_counter_binary_1/c_counter_binary_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==c_counter_binary_1 || ORIG_REF_NAME==c_counter_binary_1} -quiet] -quiet
