# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/tao/DCE/lab9/lab9_3_3/lab9_3_3.srcs/sources_1/ip/c_counter_binary_10/c_counter_binary_10.xci
# IP: The module: 'c_counter_binary_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tao/DCE/lab9/lab9_3_3/lab9_3_3.srcs/sources_1/ip/c_counter_binary_10/c_counter_binary_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_10'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /home/tao/DCE/lab9/lab9_3_3/lab9_3_3.srcs/sources_1/ip/c_counter_binary_10/c_counter_binary_10.xci
# IP: The module: 'c_counter_binary_10' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/tao/DCE/lab9/lab9_3_3/lab9_3_3.srcs/sources_1/ip/c_counter_binary_10/c_counter_binary_10_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'c_counter_binary_10'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
